version: "3.1"

services:
  s_nginx:
    container_name: c_nginx
    image: nginx
    ports:
      - 8080:80
      - 8081:80

  s_html:
    container_name: c_html
    image: httpd
    volumes:
      - C:/Users/SeydaNur/Desktop/docker-exercise/httpd/html:/usr/local/apache2/htdocs/ # takes our html file, give absolute path
    # - html:/usr/local/apache2/htdocs/ # takes httpd's own html, prints "It works!"
    ports:
      - 9090:80
      - 9091:80

volumes:
  v_html: null
